// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfwisaovjymznoqaomcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmd2lzYW92anltem5vcWFvbWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjgyMDcsImV4cCI6MjA2NDQ0NDIwN30.GWQVFNOd9G4IGy-nklCW-51tx9nXgHh3WxEAExpPXeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);